### ISSUE TITLE
Feature request - additional ping fields/multiple role pings from one reminder/interval?

### ISSUE THREAD

**Issue by vKakaru** [meister03/bump-reminder-docs#1]
Unsure if it is currently possible, or could be implemented...  Could being able to manually add another ping role field be allowed, or allow multiple roles to be selected in the current ping fields for intervals and reminders?

**Comment by meister03** [comment]
@Kakarifers `%setup ping @role1@role2@role3`

**Comment by vKakaru** [comment]
That's for the bump channel though, correct?  I was following along with the syntax of the setup for a /remind create.

**Comment by meister03** [comment]
> That's for the bump channel though, correct? I was following along with the syntax of the setup for a /remind create.

You can use the message command works similar
